<?php

declare(strict_types=1);

namespace Unknowncoder\Teleport\Registry;

use Unknowncoder\Teleport\Scanner\FileScanner;
use Unknowncoder\Teleport\Scanner\FunctionParser;

/**
 * Class MapGenerator
 *
 * Scans PHP files, extracts function definitions, and compiles sharded,
 * high-performance static map caches for the Warp dispatcher.
 *
 * @package Unknowncoder\Teleport\Registry
 */
class MapGenerator
{
    protected FileScanner $scanner;
    protected FunctionParser $parser;

    /**
     * MapGenerator constructor.
     *
     * @param FileScanner|null $scanner
     * @param FunctionParser|null $parser
     */
    public function __construct(FileScanner $scanner = null, FunctionParser $parser = null)
    {
        $this->scanner = $scanner ?? new FileScanner();
        $this->parser = $parser ?? new FunctionParser();
    }

    /**
     * Generate simple map array of Alias => FilePath.
     *
     * @param array<string> $directories List of directories to scan.
     * @param string $basePath Base path to strip for relative paths.
     * @param array<string> $excludeDirs Directory names to exclude.
     * @return array<string, string> Map of WarpAlias => FilePath.
     */
    public function generateMap(array $directories, string $basePath = '', array $excludeDirs = []): array
    {
        $detailedMap = $this->generateDetailedMap($directories, $basePath, $excludeDirs);
        $simpleMap = [];

        foreach ($detailedMap as $alias => $info) {
            $simpleMap[$alias] = $info['file'];
        }

        return $simpleMap;
    }

    /**
     * Generate detailed map array containing file paths and FQNs.
     *
     * @param array<string> $directories List of directories to scan.
     * @param string $basePath Base path to calculate relative paths against.
     * @param array<string> $excludeDirs Directory names to exclude.
     * @return array<string, array{file: string, fqn: string}> Map of WarpAlias => ['file' => ..., 'fqn' => ...].
     */
    public function generateDetailedMap(array $directories, string $basePath = '', array $excludeDirs = []): array
    {
        $files = $this->scanner->scan($directories, $excludeDirs);
        $map = [];

        foreach ($files as $file) {
            $functions = $this->parser->parseFunctions($file);
            foreach ($functions as $function) {
                // Translates App\Helpers\slugify -> App_Helpers_slugify
                $alias = str_replace('\\', '_', $function);

                $path = $file;
                if ($basePath !== '') {
                    $path = $this->getRelativePath($basePath, $file);
                }

                $map[$alias] = [
                    'file' => $path,
                    'fqn' => $function,
                ];
            }
        }

        ksort($map); // Deterministic ordering across environments

        return $map;
    }

    /**
     * Generate and write multi-file sharded cache map directory (.cache/teleport).
     *
     * @param array<string> $directories List of directories to scan.
     * @param string $outputDir Directory where cache shards and index.php will be saved.
     * @param array<string> $excludeDirs Directory names to exclude.
     * @param int $shardCount Number of shard files to partition function maps into.
     * @return bool True on success, false on failure.
     */
    public function writeShardedCache(array $directories, string $outputDir, array $excludeDirs = [], int $shardCount = 8): bool
    {
        $realOutputDir = rtrim($outputDir, '/\\');
        $shardsDir = $realOutputDir . '/shards';

        if (!is_dir($shardsDir)) {
            if (!mkdir($shardsDir, 0755, true) && !is_dir($shardsDir)) {
                return false;
            }
        }

        // Clean up existing shard files in output directory
        $existingShards = glob($shardsDir . '/*.php');
        if ($existingShards !== false) {
            foreach ($existingShards as $shardFile) {
                @unlink($shardFile);
            }
        }

        $basePath = realpath($shardsDir) ?: $shardsDir;
        $detailedMap = $this->generateDetailedMap($directories, $basePath, $excludeDirs);

        $shards = [];
        $indexShards = [];
        $shardCount = max(1, $shardCount);

        foreach ($detailedMap as $alias => $info) {
            $bucketIndex = abs(crc32($alias)) % $shardCount;
            $shardFileName = sprintf('shard_%d.php', $bucketIndex);

            $shards[$shardFileName][$alias] = $info;
            $indexShards[$alias] = 'shards/' . $shardFileName;
        }

        // Write individual shard files
        foreach ($shards as $shardFileName => $entries) {
            $shardPath = $shardsDir . '/' . $shardFileName;
            $content = "<?php\n\n";
            $content .= "// Generated by Teleport Shard Map - Do not modify manually\n\n";
            $content .= "return [\n";

            foreach ($entries as $alias => $info) {
                $aliasString = var_export($alias, true);
                $fileString = var_export(ltrim($info['file'], '/'), true);
                $fqnString = var_export($info['fqn'], true);
                $content .= "    {$aliasString} => [\n";
                $content .= "        'file' => __DIR__ . '/' . {$fileString},\n";
                $content .= "        'fqn' => {$fqnString},\n";
                $content .= "    ],\n";
            }

            $content .= "];\n";

            if (file_put_contents($shardPath, $content) === false) {
                return false;
            }
        }

        // Write master index file
        $indexPath = $realOutputDir . '/index.php';
        $indexContent = "<?php\n\n";
        $indexContent .= "// Generated by Teleport Master Index - Do not modify manually\n\n";
        $indexContent .= "return [\n";
        $indexContent .= "    'shards' => [\n";

        ksort($indexShards);
        foreach ($indexShards as $alias => $shardFile) {
            $indexContent .= "        '{$alias}' => '{$shardFile}',\n";
        }

        $indexContent .= "    ],\n";
        $indexContent .= "];\n";

        return file_put_contents($indexPath, $indexContent) !== false;
    }

    /**
     * Generate and write a single legacy map file (for backwards compatibility).
     *
     * @param array<string> $directories List of directories to scan.
     * @param string $outputPath Where to save the map file.
     * @param bool $relative Whether to use relative paths in the generated map.
     * @return bool True on success, false on failure.
     */
    public function writeMapFile(array $directories, string $outputPath, bool $relative = false): bool
    {
        $realOutputPath = dirname($outputPath);
        if ($realOutputPath !== '' && !is_dir($realOutputPath)) {
            mkdir($realOutputPath, 0755, true);
        }

        $basePath = $relative ? (realpath($realOutputPath) ?: $realOutputPath) : '';
        $map = $this->generateMap($directories, $basePath);

        $content = "<?php\n\n";
        $content .= "// Generated by Teleport - Do not modify manually\n\n";
        $content .= "return [\n";
        foreach ($map as $alias => $path) {
            $aliasString = var_export($alias, true);
            if ($relative) {
                $fileString = var_export(ltrim($path, '/'), true);
                $content .= "    {$aliasString} => __DIR__ . '/' . {$fileString},\n";
            } else {
                $fileString = var_export($path, true);
                $content .= "    {$aliasString} => {$fileString},\n";
            }
        }
        $content .= "];\n";

        return file_put_contents($outputPath, $content) !== false;
    }

    /**
     * Compute a relative path from a directory to a target file.
     *
     * @param string $from Directory path.
     * @param string $to Target file path.
     * @return string Relative path.
     */
    public function getRelativePath(string $from, string $to): string
    {
        $from = str_replace('\\', '/', realpath($from) ?: $from);
        $to = str_replace('\\', '/', realpath($to) ?: $to);

        $fromParts = explode('/', rtrim($from, '/'));
        $toParts = explode('/', rtrim($to, '/'));

        while (count($fromParts) && count($toParts) && $fromParts[0] === $toParts[0]) {
            array_shift($fromParts);
            array_shift($toParts);
        }

        return str_repeat('../', count($fromParts)) . implode('/', $toParts);
    }
}
